name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
depend: [DiscordSRV]
softdepend: [CoreProtect, Vault, WorldEdit]
author: Rude Yeti, Incorporated
load: POSTWORLD
description: ${project.description}
commands:
  necessity:
    description: necessity
    aliases: [ns]
  serveractivity:
    description: serveractivity
    aliases: [sa, activity]